# Generated by Django 6.1.1 on 2026-10-06 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.department'),
        ),
        migrations.CreateModel(
            name='ProcurementMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_status', models.CharField(choices=[('PENDING_ORIGINATING_HOD', 'Pending Originating HOD Approval'), ('PENDING_CM_APPROVAL_1', 'Pending Council Manager Approval (Memo)'), ('PENDING_PROCUREMENT', 'Pending Procurement Department'), ('PENDING_QUOTES_VOUCHER', 'Pending Quotes & Voucher (Originating Dept)'), ('PENDING_CM_APPROVAL_2', 'Pending Council Manager Approval (Voucher)'), ('PENDING_BUDGET', 'Pending Budget Department'), ('PENDING_AUDIT', 'Pending Audit Department'), ('PENDING_PAY_OFFICE', 'Pending Pay Office Release'), ('FUNDS_RELEASED_TO_HOD', 'Funds Released to Originating HOD'), ('COMPLETED', 'Executed by Contractor'), ('REJECTED', 'Rejected/Cancelled')], default='PENDING_ORIGINATING_HOD', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('originating_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memos', to='accounts.department')),
                ('originating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
